# SPDX-License-Identifier: Apache-2.0
# Originally developed by Telicent Ltd.; subsequently adapted, enhanced, and maintained by the National Digital Twin Programme.

# common-configuration.properties

# ============================================
# Identity Provider (IDP) Configuration
# ============================================

# Enable mutual TLS for IDP communication
idp.mtls.enabled=false
idp.tls.enabled=true

idp.jwks.url=https://host.docker.internal:8443/realms/management-node/protocol/openid-connect/certs
idp.token.url=https://host.docker.internal:8443/realms/management-node/protocol/openid-connect/token
idp.token.backoff=1000

idp.truststore.path=/app/truststore.jks
idp.truststore.password=changeit

idp.keystore.path=/app/client.p12
idp.keystore.password=changeit

# OAuth2 client ID (registered with the IDP)
idp.client.id=ztf-client
idp.client.secret=





