# SPDX-License-Identifier: Apache-2.0
# Originally developed by Telicent Ltd.; subsequently adapted, enhanced, and maintained by the National Digital Twin Programme.

# Copyright (c) Telicent Ltd.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Modifications made by the National Digital Twin Programme (NDTP)
# © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme
# and is legally attributed to the Department for Business and Trade (UK) as the governing entity.


# Application Base Image
FROM eclipse-temurin:21 AS app-base
RUN apt-get update && \
    apt-get install -y --no-install-recommends dumb-init && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ARG PROJECT_VERSION
ARG ARTIFACT_ID=federator

RUN mkdir -p /app/ /app/lib/ /app/agents/ /opt/ianode/sbom/ && \
    groupadd appgroup && \
    useradd -Mg appgroup ianode-service && \
    chown -R :appgroup /app/ /app/lib/ /app/agents/ /opt/ianode/sbom/
WORKDIR /app
USER ianode-service
ENV PROJECT_VERSION=${PROJECT_VERSION}
ENV ARTIFACT_ID=${ARTIFACT_ID}

COPY target/${ARTIFACT_ID}-${PROJECT_VERSION}-bom.json /opt/ianode/sbom/

# Federation Server
FROM app-base AS federation-server
COPY target/${ARTIFACT_ID}-server-${PROJECT_VERSION}.jar /app/lib/app.jar
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["java", "-cp", "/app/lib/app.jar:/library/*", "uk.gov.dbt.ndtp.federator.FederatorServer"]

# Federation Client
FROM app-base AS federation-client
COPY target/${ARTIFACT_ID}-client-${PROJECT_VERSION}.jar /app/lib/app.jar
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["java", "-jar", "/app/lib/app.jar"]
