# SPDX-License-Identifier: Apache-2.0
# Originally developed by Telicent Ltd.; subsequently adapted, enhanced, and maintained by the National Digital Twin Programme.

# Copyright (c) Telicent Ltd.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Modifications made by the National Digital Twin Programme (NDTP)
# © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme
# and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

# syntax=docker/dockerfile:1.2

FROM eclipse-temurin:21 AS federator

RUN apt-get update \
 && apt-get upgrade -y openssl libssl3t64 \
 && rm -rf /var/lib/apt/lists/*

LABEL org.opencontainers.image.source=https://github.com/National-Digital-Twin/federator

RUN mkdir -p /library/ /app/ && \
	groupadd appgroup && \
	useradd -Mg appgroup federator-service && \
	chown -R :appgroup /library/ /app/
WORKDIR /app
ARG JAR_NAME
COPY target/${JAR_NAME}.jar /app/app.jar
USER federator-service
ENTRYPOINT java -cp /app/app.jar:/library/* $PROPERTIES uk.gov.dbt.ndtp.federator.FederatorClient $ARGS

# Federation Client with MSK auth support
FROM federator AS federator-msk
USER root
RUN mkdir -p /baked-library/ && \
	groupadd appgroup && \
	useradd -Mg appgroup federator-service && \
	chown -R :appgroup /baked-library/
ARG MSK_VERSION=2.3.7
ADD --chmod=644 https://github.com/aws/aws-msk-iam-auth/releases/download/v${MSK_VERSION}/aws-msk-iam-auth-${MSK_VERSION}-all.jar /baked-library/
USER federator-service
ENTRYPOINT java -cp /baked-library/*:/library/*:/app/app.jar $PROPERTIES uk.gov.dbt.ndtp.federator.FederatorClient $ARGS
