apiVersion: v1
kind: ConfigMap
metadata:
  name: federator-common-config-client
  namespace: {{ .Release.Namespace }}
data:
  common-configuration.properties: |
    idp.mtls.enabled=true

    idp.client.id={{ .Values.federatorClient.idp.clientId }}

    idp.jwks.url={{ .Values.federatorClient.idp.jwksUrl }}
    idp.token.url={{ .Values.federatorClient.idp.tokenUrl }}
    idp.token.backoff={{ .Values.federatorClient.idp.tokenBackoff }}

    idp.truststore.path={{ .Values.federatorClient.idp.truststorePath }}
    idp.truststore.password=

    idp.keystore.path={{ .Values.federatorClient.idp.keystorePath }}
    idp.keystore.password=

    vault.uri={{ .Values.vaultConfig.uri }}
    vault.truststore.path={{ .Values.vaultConfig.truststorePath }}
    vault.truststore.password={{ .Values.vaultConfig.truststorePassword }}

    idp.auth.mode={{ .Values.federatorClient.idp.authMode }}
    idp.jwt.algorithm={{ .Values.federatorClient.idp.jwtAlgorithm }}
    idp.jwt.key.alias={{ .Values.federatorClient.idp.jwtKeyAlias }}
