{{- if .Values.keyvault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: federator-server-kv-secrets
  namespace: {{ .Release.Namespace }}

spec:
  provider: azure

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "{{ .Values.keyvault.clientID }}"
    keyvaultName: "{{ .Values.keyvault.name }}"
    tenantId: "{{ .Values.keyvault.tenantId }}"

    objects: |
      array:
        - |
          objectName: STORAGE-CONNECTION-STRING
          objectType: secret

  secretObjects:
    - secretName: federator-server-secrets
      type: Opaque
      data:
        - objectName: STORAGE-CONNECTION-STRING
          key: STORAGE_CONNECTION_STRING
{{- end }}
