# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme
# and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Release

env:
  MAVEN_CLI_OPTS: "--batch-mode --no-transfer-progress"

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:
    # To eventually be replaced with just using the version from the pom
    inputs:
      image_tag:
        description: Tag for the docker image
        required: true
        type: string
      dry_run:
        description: |
          Dry run.
          Toggle for whether to push images or not.
          If toggled then the built images will not be pushed.
        required: false
        default: false
        type: boolean

jobs:
  # Make sure that the current code runs
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: |
      github.event.pull_request.merged == true &&
      (startsWith(github.head_ref, 'release/') || startsWith(github.head_ref, 'hotfix/'))
    outputs:
      project_version: ${{ steps.get-version.outputs.project_version }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Setup Java/Maven
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: 21
          distribution: "temurin"
          cache: maven
          server-password: "GH_PACKAGES_PAT"
      - name: Get version
        id: get-version
        run: echo project_version=$(./mvnw $MAVEN_CLI_OPTS help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_OUTPUT
      - name: Build packages
        env:
          GH_PACKAGES_PAT: ${{ secrets.GH_PACKAGES_PAT }}
        run: ./mvnw $MAVEN_CLI_OPTS package
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        name: Persist server
        id: persist-server
        with:
          name: federator-server-${{ steps.get-version.outputs.project_version }}.jar
          path: target/federator-server-${{ steps.get-version.outputs.project_version }}.jar
          retention-days: 1
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        name: Persist client
        with:
          name: federator-client-${{ steps.get-version.outputs.project_version }}.jar
          path: target/federator-client-${{ steps.get-version.outputs.project_version }}.jar
          retention-days: 1

  publish:
    name: Publish to github packages
    needs: verify
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    outputs:
      image_tag: ${{ steps.get_version.outputs.version }}
    env:
      GITHUB_ACTOR: ${{ github.actor }}
      GH_PACKAGES_PAT: ${{ secrets.GH_PACKAGES_PAT }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Setup Java/Maven
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: 21
          distribution: "temurin"
          cache: maven
          server-password: "GH_PACKAGES_PAT"
      - name: Build packages
        run: ./mvnw $MAVEN_CLI_OPTS package -DskipTests
      - name: Publish package
        run: ./mvnw $MAVEN_CLI_OPTS deploy -DskipTests --settings .m2/settings.xml
      - name: get image tag from branch
        id: get_version
        run: |
          BRANCH="${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}"
          VERSION="${BRANCH#release/}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  release-ghcr:
    name: "Build and release docker images to GHCR with tags '${{ needs.publish.outputs.image_tag }} latest'"
    needs:
     - verify
     - publish
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/docker-ghcr.yml
    secrets: inherit
    with:
      image_tag: "${{ needs.publish.outputs.image_tag }},latest"
      jar_version: ${{ needs.verify.outputs.project_version }}
      dry_run: false
      docker_target: federator

  cleanup:
    name: Artifact cleanup
    runs-on: ubuntu-latest
    permissions:
      actions: write
    needs:
      - release-ghcr
      - verify
    if: ${{ needs.verify.result == 'success' }}
    steps:
      - uses: geekyeggo/delete-artifact@f275313e70c08f6120db482d7a6b98377786765b # v5.1.0
        name: Delete server artifact
        with:
          name: federator-server-${{ needs.verify.outputs.project_version }}.jar
      - uses: geekyeggo/delete-artifact@f275313e70c08f6120db482d7a6b98377786765b # v5.1.0
        name: Delete client artifact
        with:
          name: federator-client-${{ needs.verify.outputs.project_version }}.jar
